sude: required
services:
    - docker

before_install:
    - docker build -t kamranmirzeyev/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kamranmirzeyev/docker-react npm run test

language: generic 